In [1]:
!pip install numpy


In [2]:
import numpy as np

# 1. Create 1D NumPy array from 1 to 20
arr1d = np.arange(1, 21)

# a. Sum, Mean, Median, Std Dev
print("Sum:", np.sum(arr1d))
print("Mean:", np.mean(arr1d))
print("Median:", np.median(arr1d))
print("Standard Deviation:", np.std(arr1d))

# b. Indices of elements > 10
indices_gt_10 = np.where(arr1d > 10)
print("Indices of elements > 10:", indices_gt_10[0])

# 2. Create 2D array of shape 4x4 with numbers from 1 to 16
arr2d = np.arange(1, 17).reshape(4, 4)

# a. Print array
print("\n2D Array:\n", arr2d)

# b. Transpose of array
print("Transpose:\n", arr2d.T)

# c. Row-wise and Column-wise sums
print("Row-wise sum:", np.sum(arr2d, axis=1))
print("Column-wise sum:", np.sum(arr2d, axis=0))

# 3. Create two 3x3 arrays with random integers from 1 to 20
arrA = np.random.randint(1, 21, (3, 3))
arrB = np.random.randint(1, 21, (3, 3))

print("\nArray A:\n", arrA)
print("Array B:\n", arrB)

# a. Element-wise addition, subtraction, multiplication
print("Addition:\n", arrA + arrB)
print("Subtraction:\n", arrA - arrB)
print("Multiplication:\n", arrA * arrB)

# b. Dot product
print("Dot Product:\n", np.dot(arrA, arrB))

# 4. Reshape 1D array of size 12 to 3x4 and slice first 2 rows, last 2 columns
arr_reshaped = np.arange(1, 13).reshape(3, 4)
print("\nReshaped 3x4 Array:\n", arr_reshaped)
print("First 2 rows, Last 2 columns:\n", arr_reshaped[:2, -2:])


Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]

Array A:
 [[ 5  9 10]
 [ 9 20  2]
 [ 5 13  7]]
Array B:
 [[12 15 18]
 [ 5 14 11]
 [11 20 15]]
Addition:
 [[17 24 28]
 [14 34 13]
 [16 33 22]]
Subtraction:
 [[-7 -6 -8]
 [ 4  6 -9]
 [-6 -7 -8]]
Multiplication:
 [[ 60 135 180]
 [ 45 280  22]
 [ 55 260 105]]
Dot Product:
 [[215 401 339]
 [230 455 412]
 [202 397 338]]

Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First 2 rows, Last 2 columns:
 [[3 4]
 [7 8]]
